#!/usr/bin/env python

import re
import sys

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("dir", help='Destination director')
args = parser.parse_args()

import requests
session = requests.Session()

from lib import *

result = login(session)
if result.status_code != 200:
    print('Failed to log in', file=sys.stderr)
    sys.exit(1)

for r in get_resources(session):
    print(f"Downloading {r}")
    get_file(session, str(r), args.dir)
