#!/usr/bin/env python

import sys

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("dir", help='Destination directory')
args = parser.parse_args()

import requests
session = requests.Session()

from lib import *

result = login(session)
if result.status_code != 200:
    print('Failed to log in', file=sys.stderr)
    sys.exit(1)

images = get_images(session)

write_metadata(images, args.dir)

for i in images:
    filename = i['name'] + os.path.splitext(i['description'])[1]
    get_image(session, filename, i['download_url'], args.dir)
