#!/usr/bin/env python

import sys

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("dir", help='Destination directory')
args = parser.parse_args()

import requests
session = requests.Session()

from lib import *

result = login(session)
if result.status_code != 200:
    print('Failed to log in', file=sys.stderr)
    sys.exit(1)

resources = get_resources(session)

write_metadata(resources, args.dir)

for r in resources:
    get_file(session, r['download_url'], args.dir)
