#!/usr/bin/env python

import sys

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("dir", help='Destination directory')
args = parser.parse_args()

import requests
session = requests.Session()

from lib import *

result = login(session)
if result.status_code != 200:
    print('Failed to log in', file=sys.stderr)
    sys.exit(1)

pages = get_pages(session)

write_metadata(pages, args.dir)

for p in pages:
    get_page_editor_content(session, p['edit_url'], p['url'], args.dir)
